print('Getting to know You!')
yourName = input("What's your name?:")
favFood = input("What's your Favorite Food?:")
favMusic = input("What's your favorite music?:")
yourAddress = input("Where do you live?:")
print()

print("You are: ", yourName)
print("You are probably hungry for: ", favFood)
print("You are definitely getting your groove on to ", favMusic)
print("You live in ", yourAddress)
print("Have a great day!")
